### ISSUE TITLE
librustzcash doesn't compile with rustc 1.49.0

### ISSUE THREAD

**Issue by adityapk00** [zcash/librustzcash#333]
If you set the `rust-toolchain` to `1.49.0`, `librustzcash` compile fails with:

```
error[E0277]: cannot multiply-assign `<E as Engine>::Fr` by `&&<E as Engine>::Fr`
   --> C:\Users\Aditya Kulkarni\.cargo\registry\src\github.com-1ecc6299db9ec823\bellman-0.8.0\src\groth16\generator.rs:401:39
    |
401 |                         at.mul_assign(&beta);
    |                                       ^^^^^ no implementation for `<E as Engine>::Fr *= &&<E as Engine>::Fr`
    |
    = help: the trait `MulAssign<&&<E as Engine>::Fr>` is not implemented for `<E as Engine>::Fr`
help: consider further restricting the associated type
    |
331 |     ) where <E as Engine>::Fr: MulAssign<&&<E as Engine>::Fr> {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

With `1.48.0`, works fine.

**Comment by adityapk00** [comment]
I should clarify - I ran into this issue when compiling the zecwallet light SDK with v1.49.0 which pulls in `librustzcash`, so the `rust-toolchain` in ignored.

**Comment by str4d** [comment]
This was an issue in the `bellman` crate, which was fixed several months ago in `0.8.1`. Your error message indicates you are using `0.8.0`, which suggests you need to run `cargo update` to bump your lockfile. If that doesn't resolve your problem, then we can dig into it.

**Comment by adityapk00** [comment]
That's amazing. Thanks, that fixed it.
