### PR TITLE
zcash_pool_migration: fix redraw test broken by the #2898/#2910 semantic merge conflict

### PR DESCRIPTION
**Pull request by nuttycom**
`main` does not currently compile for `zcash_pool_migration` test targets: #2898 removed the scheduling test module's `modulus()` helper in favor of direct `AnchorBucketInterval::ZIP_318` references, and #2910 (merged immediately after) added `redraw_anchor_boundary_window_endpoints`, which calls it. Each PR was green in isolation; the textual merge was clean; the combination fails with `cannot find function `modulus``, which is what the red wall on `main`'s tip (per-feature clippy, Orchard/all-features test jobs, bitrot) reduces to.

Two-line fix: use the direct `AnchorBucketInterval::ZIP_318` reference, as the surrounding tests now do.

Opened ready-for-review rather than draft since it unbreaks `main` for everything behind it.

---

Filed with Claude Code assistance.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_016Gsndy5ri9eYvtH31DnHTQ

### CODE REVIEW

**Review by nuttycom — COMMENTED** [review]
self-utACK

**Review by pacu — APPROVED** [review]
utACK
